# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d323cabd419ca7fc2e92afb6fe7875d9eb479ae6d83bcc58e94f57910011bf6f51b759cb00e3d3e9e2c10c37d00a08cbbe9738549d5f9c46ff87ea5e7fd43a

test:
  secret_key_base: 0c8476eaf152d4e8c60730a12ff49309e8c3c9f1fd7bba20bd92402a84e2e339aaff89f623b9ffd39987aa4b8a1805c4dc8cc745de037067b2a54254550ad762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
